---
title: Gallery
lightbox: auto
execute:
  echo: false
---

```{css}
.gslide-desc {
	text-align: center;
  font-size: 1.1rem !important;
}
div.gslide-description, .gslide-desc {
	background-color: #e0e0e0 !important;
}
```

Click on a plot to get the link to its code.

::: {layout-ncol=2}

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/points-iris-boring.R){target='_blank'}"
#| file: "gallery_figs/points-iris-boring.R"
```


```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/points-iris-better.R){target='_blank'}"
#| file: "gallery_figs/points-iris-better.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/chull-penguins.R){target='_blank'}"
#| file: "gallery_figs/chull-penguins.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/boxplot-by-penguins.R){target='_blank'}"
#| file: "gallery_figs/boxplot-by-penguins.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/bubble-penguins.R){target='_blank'}"
#| file: "gallery_figs/bubble-penguins.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/bubble-quakes.R){target='_blank'}"
#| file: "gallery_figs/bubble-quakes.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/spaghetti-aq.R){target='_blank'}"
#| file: "gallery_figs/spaghetti-aq.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/direct-labels-aq.R){target='_blank'}"
#| file: "gallery_figs/direct-labels-aq.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/hist-by-penguins.R){target='_blank'}"
#| file: "gallery_figs/hist-by-penguins.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/ridge-aq.R){target='_blank'}"
#| file: "gallery_figs/ridge-aq.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/likert.R){target='_blank'}"
#| file: "gallery_figs/likert.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/spineplot-titanic.R){target='_blank'}"
#| file: "gallery_figs/spineplot-titanic.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/coefplot-mtcars.R){target='_blank'}"
#| file: "gallery_figs/coefplot-mtcars.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/simpsons-paradox.R){target='_blank'}"
#| file: "gallery_figs/simpsons-paradox.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/add-points-rug-faithful.R){target='_blank'}"
#| file: "gallery_figs/add-points-rug-faithful.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/add-ablines.R){target='_blank'}"
#| file: "gallery_figs/add-ablines.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/add-text-mtcars.R){target='_blank'}"
#| file: "gallery_figs/add-text-mtcars.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/pirate-iris.R){target='_blank'}"
#| file: "gallery_figs/pirate-iris.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/rect-by.R){target='_blank'}"
#| file: "gallery_figs/rect-by.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/polygons.R){target='_blank'}"
#| file: "gallery_figs/polygons.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/density-part-shading.R){target='_blank'}"
#| file: "gallery_figs/density-part-shading.R"
```

```{r}
#| lightbox:
#|   group: r-graph
#|   description: "[Code](https://github.com/grantmcdermott/tinyplot/blob/main/vignettes/gallery_figs/polygon-valentine.R){target='_blank'}"
#| file: "gallery_figs/polygon-valentine.R"
```

:::
